
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet-sonarscanner
      # You may pin to the exact commit or the version.
      # uses: Secbyte/dotnet-sonarscanner@10230bbd60c5b727532504308cba3c6577deba14
      uses: Secbyte/dotnet-sonarscanner@v2.3
      with:
        # Command to invoke build
        buildCommand: dotnet build .
        # Command to invoke tests
        testCommand: dotnet test .
        # Specifies the key of the analyzed project in SonarQube
        projectKey: acpkhan85_clean
        # Specifies the name of the analyzed project in SonarQube
        projectName: clean
        # The server URL
        sonarHostname: https://sonarcloud.io
        # Organisation
        sonarOrganisation: acpkhan85
     
